### ISSUE TITLE
Error loading express-routes-mapper

### ISSUE THREAD

**Issue by KrikriG** [aichbauer/express-graphql-boilerplate#29]
When I start the application using npm run dev or npm start, i have the following error:

TypeError: mapRoutes is not a function
    at Object.<anonymous> (D:\Users\cguerlus\Documents\02_Développement\Projets\boilerplate\express-graphql-boilerplate\api\api.js:30:22)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3

Do you have an idea. It seems that the express-routes-mapper is not well loaded but dont find why 

Regards,
Christophe

**Comment by aichbauer** [comment]
for right now downgrading `express-routes-mapper` to version `1.0.2` would do the trick.

So in your package json change `express-routes-mapper: "^1.0.2"` to `express-routes-mapper: "1.0.2"`

But we are working on a fix for it in the `express-routes-mapper` package, than we should update to the new routes-mapper version.

Thanks for reporting the issue.

**Comment by KrikriG** [comment]
OK it works

thanks !

**Comment by aichbauer** [comment]
aichbauer/express-routes-mapper#25

This should fix this behaviour. It should be possible to use `^1.0.2` again as soon as this PR gets merged and the new version is published.

**Comment by aichbauer** [comment]
Problem should be fixed due to the merge of: [aichbauer/express-routes-mapper#25](https://github.com/aichbauer/express-routes-mapper/pull/25)
